# For more info on HTTP files go to https://aka.ms/vs/httpfile
POST https://localhost:7143/arduino?TemperatureC=11&Humidity=33&MethaneGas=22&HydrogenGas=77
###

GET https://protect.somee.com/arduino?limit=20
###

DELETE https://localhost:7143/arduino
###