// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RealTimeMonitoringUTS.Data;

#nullable disable

namespace RealTimeMonitoringUTS.Data.Migrations
{
    [DbContext(typeof(RealTimeMonitoringDbContext))]
    [Migration("20251026061646_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RealTimeMonitoringUTS.Data.Model.Sensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("AddAt");

                    b.Property<int>("Humidity")
                        .HasColumnType("int")
                        .HasColumnName("Humidity");

                    b.Property<int>("HydrogenGas")
                        .HasColumnType("int")
                        .HasColumnName("HydrogenGas");

                    b.Property<int>("MethaneGas")
                        .HasColumnType("int")
                        .HasColumnName("MethaneGas");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("int")
                        .HasColumnName("Temperature");

                    b.HasKey("Id");

                    b.ToTable("Sensor", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
