// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RealTimeMonitoringUTS.Data;

#nullable disable

namespace RealTimeMonitoringUTS.Data.Migrations
{
    [DbContext(typeof(RealTimeMonitoringDbContext))]
    partial class RealTimeMonitoringDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RealTimeMonitoringUTS.Data.Model.Sensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("AddAt");

                    b.Property<decimal>("AlcohonGas")
                        .HasColumnType("DECIMAL(10, 2)")
                        .HasColumnName("AlcohonGas");

                    b.Property<decimal>("Humidity")
                        .HasColumnType("DECIMAL(10, 2)")
                        .HasColumnName("Humidity");

                    b.Property<decimal>("HydrogenGas")
                        .HasColumnType("DECIMAL(10, 2)")
                        .HasColumnName("HydrogenGas");

                    b.Property<decimal>("LpgGas")
                        .HasColumnType("DECIMAL(10, 2)")
                        .HasColumnName("LpgGas");

                    b.Property<decimal>("MethaneGas")
                        .HasColumnType("DECIMAL(10, 2)")
                        .HasColumnName("MethaneGas");

                    b.Property<decimal>("Smoke")
                        .HasColumnType("DECIMAL(10, 2)")
                        .HasColumnName("Smoke");

                    b.Property<decimal>("TemperatureC")
                        .HasColumnType("DECIMAL(10, 2)")
                        .HasColumnName("TemperatureC");

                    b.Property<int>("X")
                        .HasColumnType("int")
                        .HasColumnName("X");

                    b.Property<int>("Y")
                        .HasColumnType("int")
                        .HasColumnName("Y");

                    b.Property<int>("Z")
                        .HasColumnType("int")
                        .HasColumnName("Z");

                    b.HasKey("Id");

                    b.ToTable("Sensor", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
